apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: thesis
data:
  NEXT_PUBLIC_BACKEND_URL: "http://k8s-thesis-appingre-ca8a13505b-717776459.ap-southeast-2.elb.amazonaws.com/api"
  NODE_ENV: "production"
